version: '3.2'
services:
  web:
    build: .
    restart: always
    ports:
     - "50000:50000"
    volumes:
     - .:/code
    networks:
      - app-tierx-evn

networks:
  app-tierx-evn:
    driver: bridge